# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check Git Status
on:
  workflow_dispatch:
 
jobs:
  checkgitstatus:
    runs-on: ubuntu-latest
    steps:
      - name: Space Check
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          du -h --total | grep total
#       - uses: actions/checkout@v2
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Setup Github Config
#         run: |
#           git config --global user.name "saikr789"
#           git config --global user.email "saikrishna.nama@msitprogram.net"
     
#       - name: Check Git Status
#         run: |
#           df -h --total | grep total
#           python create_simulation_files.py
          
#       - name: Commiting New Files
#         run: |
#           git pull origin master
#           git add .
#           git commit -m "`date +'%d-%m-%Y'`"
#           git push origin master
          
  newsimulation30:
    name: newsimulation30
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Removing Unnecessary Files
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create New Simulation 30
        continue-on-error: true
        run: |
          python newsimulation30.py
      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
      - name: Commiting New Files
        run: |
          git pull origin master
          git add *
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master
          
  newsimulation60:
    name: newsimulation60
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Removing Unnecessary Files
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create New Simulation 60
        continue-on-error: true
        run: |
          python newsimulation60.py
      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
      - name: Commiting New Files
        run: |
          git pull origin master
          git add *
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master
          
  newsimulation90:
    name: newsimulation90
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Removing Unnecessary Files
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create New Simulation 90
        continue-on-error: true
        run: |
          python newsimulation90.py
      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
      - name: Commiting New Files
        run: |
          git pull origin master
          git add *
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master
  newsimulation180:
    name: newsimulation180
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Removing Unnecessary Files
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create New Simulation 180
        continue-on-error: true
        run: |
          python newsimulation180.py
      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
      - name: Commiting New Files
        run: |
          git pull origin master
          git add *
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master
          
  newsimulation360:
    name: newsimulation360
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Removing Unnecessary Files
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create New Simulation 360
        continue-on-error: true
        run: |
          python newsimulation360.py
      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
      - name: Commiting New Files
        run: |
          git pull origin master
          git add *
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master
              
  newsimulation720:
    name: newsimulation720
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Removing Unnecessary Files
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create New Simulation 720
        continue-on-error: true
        run: |
          python newsimulation720.py
      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
      - name: Commiting New Files
        run: |
          git pull origin master
          git add *
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master
              
  createstopfiles:
    name: createstopfiles
    needs: [newsimulation30, newsimulation60, newsimulation90, newsimulation180, newsimulation360, newsimulation720]
    runs-on: ubuntu-latest
    steps:
      - name: Removing Unnecessary Files
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create Top Files
        run: |
          python create_top_files.py
      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
      - name: Commiting New Files
        run: |
          git pull origin master
          git add *
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master
