# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check Git Status
on:
  workflow_dispatch:
 
jobs:

  checkgitstatus:
    runs-on: ubuntu-latest

    steps:
      - name: Space Check
        run: |
          df -h
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          df -h
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
     
      - name: Check Git Status
        run: |
          df -h --total | grep total
          python create_simulation_files.py
          
      - name: Commiting New Files
        run: |
          git pull origin master
          git add *
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master
