# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Perform Operations Daily - Index, RiskFreeRate, Stock Scrape and Feature Creation
on:
  workflow_dispatch:
  schedule:
    - cron: "30 15 * * *"
jobs:
  scraping:
    name : scraping
    runs-on: ubuntu-latest
    steps:
      - name: Removing Unnecessary Files
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
          
      - name: Index and Risk Free Rate Scrape
        continue-on-error: true
        run: |
          python index_scrape.py
          python index_scrape.py
          python risk_free_rate_scrape.py
          python risk_free_rate_scrape.py

      - name: Stock Scrape
        run: |
          python dailystock.py

      - name: Commit Files
        continue-on-error: true
        run: |
          git pull origin master
          git add Data/Index.csv
          git add Data/sp500.csv
          git commit -m "Index `date +'%d-%m-%Y'`"
          git add Data/RiskFreeRateFull.csv
          git add Data/RiskFreeRate.csv
          git commit -m "Risk Free Rate `date +'%d-%m-%Y'`"
          git add Data/Stock
          git commit -m "stock `date +'%d-%m-%Y'`"
          git push origin master
  
  featurecreation:
    name : featurecreation
    needs:  [scraping]
    runs-on: ubuntu-latest
    steps:
      - name: Removing Unnecessary Files
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Github Config
        run: |
          git config --global user.name "saikr789"
          git config --global user.email "saikrishna.nama@msitprogram.net"
          
      - name: Feature Creation
        continue-on-error: true
        run: |
          python feature_creation_daily.py

      - name: Commit Files
        continue-on-error: true
        run: |
          git pull origin master
          git add Data/GRStock
          git commit -m "gr stock `date +'%d-%m-%Y'`"
          git push origin master
    
